version: "3.8"

services:
  web:
    build: ./web
    ports:
      - "8080:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
